version: "3.8"
services:
  postgres:
    container_name: react-flix-postgres
    image: postgres:latest
    hostname: tmdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tmdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    

  api:
    image: ultr444/tmdb-api:1.0
    hostname: tmdb-api
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tmdb:5432/tmdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - postgres
   

  frontend:
    image: ultr444/react-flix:1.0
    hostname: react-flix
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      - VITE_IMG=https://image.tmdb.org/t/p/w500/


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1